#!/bin/bash
if [ $# -lt 1 ] 
then
    echo "!Usage : $0 <youtube_file_link>"
    echo "e.g : $0 http://www.youtube.com/watch?v=D1R-jKKp3NA"
else
    ytquality="worst"
    omxvolume=-2000
    if [ $# -ge 2 ]; then
        omxvolume=$2    
	fi
    if [ $# -ge 3 ];then
        ytquality=$3
	fi
	echo "Quality : $ytquality volume : $omxvolume"
 #Some safety so we don't run this a bajillion times
    omx=`pgrep omxplayer | wc -l`
    yt=`pgrep youtube | wc -l`
    ytsearch=`pgrep youtube-search | wc -l`
    yt=$((yt - ytsearch))
    if [[ "$omx" -gt 0 ]] || [[ $yt -gt 2 ]] ; then
        exit 0
    fi
    if [ -z $DISPLAY ] ; then
        run_command="omxplayer  -o both --vol $omxvolume"
    else
        run_command="xterm -fullscreen -bg black -fg black -e omxplayer -o both --vol $omxvolume"
    fi
    var=$1
    http=`echo "$var" | grep "http\|yt" | wc -l`
    if [[ http -eq 0 ]] ; then
        count=`echo "$var" | wc -l`
        num=1
        while [ $num -le $count ] ;
        do
            video=`echo "$var" | head -n $num | tail -n 1`
            if [[ "$video" == yt* ]] ; then
                video="${video/yt/http}"
            fi
            todnload=`youtube-dl -i -f $ytquality -g --cookies /dev/shm/youtube_cookie.txt "$video"`
            
            $run_command "$todnload"
            num=`expr $num + 1`
        done
    else
    list=`echo "$var" | grep list | wc -l`
    if [[ list -eq 0 ]] ; then
        if [[ "$var" == yt* ]] ; then
            var="${var/yt/http}"
        fi
        todnload=`youtube-dl -i -f $ytquality -g --cookies /dev/shm/youtube_cookie.txt "$var"`
        tot=`echo "$todnload" | wc -l`
        num=1
        while [ $num -le $tot ] ; 
        do
            echo "$num outi of $tot"
            link=`echo "$todnload" | head -n $num | tail -n 1`
			echo "$run_command "$todnload""
            $run_command "$link"
            num=`expr $num + 1`
        done
    else
        echo "Youtube playlist ..."
        num=1
        if [[ "$var" == yt* ]] ; then
            var="${var/yt/http}"
        fi
        todnload=`youtube-dl -f $ytquality -g --cookies /dev/shm/youtube_cookie.txt --playlist-start $num --playlist-end $num "$var"`
        while [ "$todnload" != "" ] ; 
        do
            $run_command "$todnload"
            num=`expr $num + 1`
            if [[ "$var" == yt* ]] ; then
                var="${var/yt/http}"
            fi
            todnload=`youtube-dl -f $ytquality -g --cookies /dev/shm/youtube_cookie.txt --playlist-start $num --playlist-end $num "$var"`
        done
    fi
    fi
fi
